use_frameworks!

platform :ios, '9.0'

target 'AwesomeTooltip_Example' do
  pod 'AMPopTip', '~> 3.3.0'
  pod 'AwesomeTooltip', :path => '../'

  target 'AwesomeTooltip_Tests' do
    inherit! :search_paths

    
  end
end
